{
 "title": "properties cfstat",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "data_type",
    "label": "data_type",
    "query": "\"props-hashes-data_cf\",\"props-hashes-default\",\"props-lists-data_cf\",\"props-lists-default\",\"props-sets-default\",\"props-sets-member_cf\",\"props-strings\",\"props-zsets-data_cf\",\"props-zsets-default\",\"props-zsets-score_cf\", "
   },
   {
    "name": "cfstats_actual",
    "label": "cfstats_actual",
    "query": "AvgSec,CompactedFiles,NumFiles,ReadMBps,Score,SizeBytes,WriteAmp,WriteMBps,"
   },
   {
    "name": "cfstats_rate",
    "label": "cfstats_rate",
    "query": "CompCount,CompMergeCPU,CompSec,KeyDrop,KeyIn,MovedGB,ReadGB,RnGB,Rnp1GB,WnewGB,WriteGB"
   },
   {
    "name": "stalls",
    "label": "stalls",
    "query": "cf_l0_file_count_limit_delays_with_ongoing_compaction,cf_l0_file_count_limit_stops_with_ongoing_compaction,l0_file_count_limit_delays,l0_file_count_limit_stops,memtable_limit_delays,memtable_limit_stops,pending_compaction_bytes_delays,pending_compaction_bytes_stops,total_delays,total_stops,"
   }
  ]
 },
 "panels": [
  {
   "title": "cfstat actual $cfstats_actual",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "repeat": "cfstats_actual",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L0:$cfstats_actual\"}",
     "legendFormat": "L0"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L1:$cfstats_actual\"}",
     "legendFormat": "L1"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L2:$cfstats_actual\"}",
     "legendFormat": "L2"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L3:$cfstats_actual\"}",
     "legendFormat": "L3"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L4:$cfstats_actual\"}",
     "legendFormat": "L4"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:Sum:$cfstats_actual\"}",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "cfstat rate $cfstats_rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "repeat": "cfstats_rate",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L0:$cfstats_rate\"}[1m])",
     "legendFormat": "L0"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L1:$cfstats_rate\"}[1m])",
     "legendFormat": "L1"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L2:$cfstats_rate\"}[1m])",
     "legendFormat": "L2"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L3:$cfstats_rate\"}[1m])",
     "legendFormat": "L3"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L4:$cfstats_rate\"}[1m])",
     "legendFormat": "L4"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:Sum:$cfstats_rate\"}[1m])",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "cfstat stalls $stalls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 45 },
   "repeat": "stalls",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"$stalls\"}",
     "legendFormat": "{{flag}}"
    }
   ]
  }
 ]
}