{
 "title": "properties all",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "data_type",
    "label": "data_type",
    "query": "\"props-hashes-data_cf\",\"props-hashes-default\",\"props-lists-data_cf\",\"props-lists-default\",\"props-sets-default\",\"props-sets-member_cf\",\"props-strings\",\"props-zsets-data_cf\",\"props-zsets-default\",\"props-zsets-score_cf\", "
   },
   {
    "name": "rate",
    "label": "rate",
    "query": "engine:min_log_number_to_keep,engine:min_obsolete_sst_number_to_keep,"
   },
   {
    "name": "cfstats_actual",
    "label": "cfstats_actual",
    "query": "AvgSec,CompactedFiles,NumFiles,ReadMBps,Score,SizeBytes,WriteAmp,WriteMBps,"
   },
   {
    "name": "cfstats_rate",
    "label": "cfstats_rate",
    "query": "CompCount,CompMergeCPU,CompSec,KeyDrop,KeyIn,MovedGB,ReadGB,RnGB,Rnp1GB,WnewGB,WriteGB"
   },
   {
    "name": "io_stalls",
    "label": "io_stalls",
    "query": "level0_numfiles,level0_numfiles_with_compaction,level0_slowdown,level0_slowdown_with_compaction,memtable_compaction,memtable_slowdown,slowdown_for_pending_compaction_bytes,stop_for_pending_compaction_bytes,total_slowdown,total_stop,"
   },
   {
    "name": "leveldataflag",
    "label": "leveldataflag",
    "query": "\"data_size\",\"index_size\",\"num_data_blocks\",\"num_deletions\",\"num_entries\",\"raw_key_size\",\"raw_value_size\","
   }
  ]
 },
 "panels": [
  {
   "title": "immutable_mem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:num_immutable_mem_table{job=$data_type}",
     "legendFormat": "engine:num_immutable_mem_table"
    },
    {
     "expr": "engine:num_immutable_mem_table_flushed{job=$data_type}",
     "legendFormat": "engine:num_immutable_mem_table_flushed"
    }
   ]
  },
  {
   "title": "num_running",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:num_running_flushes{job=$data_type}",
     "legendFormat": "engine:num_running_flushes"
    },
    {
     "expr": "engine:num_running_compactions{job=$data_type}",
     "legendFormat": "engine:num_running_compactions"
    }
   ]
  },
  {
   "title": "mem_table size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:cur_size_active_mem_table{job=$data_type}",
     "legendFormat": "engine:cur_size_active_mem_table"
    },
    {
     "expr": "engine:cur_size_all_mem_tables{job=$data_type}",
     "legendFormat": "engine:cur_size_all_mem_tables"
    },
    {
     "expr": "engine:size_all_mem_tables{job=$data_type}",
     "legendFormat": "engine:size_all_mem_tables"
    }
   ]
  },
  {
   "title": "mem_table num",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:num_entries_active_mem_table{job=$data_type}",
     "legendFormat": "engine:num_entries_active_mem_table"
    },
    {
     "expr": "engine:num_entries_imm_mem_tables{job=$data_type}",
     "legendFormat": "engine:num_entries_imm_mem_tables"
    },
    {
     "expr": "engine:num_deletes_active_mem_table{job=$data_type}",
     "legendFormat": "engine:num_deletes_active_mem_table"
    },
    {
     "expr": "engine:num_deletes_imm_mem_tables{job=$data_type}",
     "legendFormat": "engine:num_deletes_imm_mem_tables"
    }
   ]
  },
  {
   "title": "estimate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:estimate_num_keys{job=$data_type}",
     "legendFormat": "engine:estimate_num_keys"
    },
    {
     "expr": "engine:estimate_table_readers_mem{job=$data_type}",
     "legendFormat": "engine:estimate_table_readers_mem"
    },
    {
     "expr": "engine:estimate_live_data_size{job=$data_type}",
     "legendFormat": "engine:estimate_live_data_size"
    },
    {
     "expr": "engine:estimate_pending_compaction_bytes{job=$data_type}",
     "legendFormat": "engine:estimate_pending_compaction_bytes"
    }
   ]
  },
  {
   "title": "engine:is_file_deletions_enabled",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:is_file_deletions_enabled{job=$data_type}",
     "legendFormat": "engine:is_file_deletions_enabled"
    }
   ]
  },
  {
   "title": "engine:background_errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:background_errors{job=$data_type}",
     "legendFormat": "engine:background_errors"
    }
   ]
  },
  {
   "title": "engine:num_live_versions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:num_live_versions{job=$data_type}",
     "legendFormat": "engine:num_live_versions"
    }
   ]
  },
  {
   "title": "sst_files_size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:total_sst_files_size{job=$data_type}",
     "legendFormat": "engine:total_sst_files_size"
    },
    {
     "expr": "engine:live_sst_files_size{job=$data_type}",
     "legendFormat": "engine:live_sst_files_size"
    }
   ]
  },
  {
   "title": "engine:base_level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:base_level{job=$data_type}",
     "legendFormat": "engine:base_level"
    }
   ]
  },
  {
   "title": "snapshots",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:num_snapshots{job=$data_type}",
     "legendFormat": "engine:num_snapshots"
    },
    {
     "expr": "engine:oldest_snapshot_time{job=$data_type}",
     "legendFormat": "engine:oldest_snapshot_time"
    },
    {
     "expr": "engine:oldest_snapshot_sequence{job=$data_type}",
     "legendFormat": "engine:oldest_snapshot_sequence"
    }
   ]
  },
  {
   "title": "num_files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:num_files_at_level0{job=$data_type}",
     "legendFormat": "engine:num_files_at_level0"
    },
    {
     "expr": "engine:num_files_at_level1{job=$data_type}",
     "legendFormat": "engine:num_files_at_level1"
    },
    {
     "expr": "engine:num_files_at_level2{job=$data_type}",
     "legendFormat": "engine:num_files_at_level2"
    },
    {
     "expr": "engine:num_files_at_level3{job=$data_type}",
     "legendFormat": "engine:num_files_at_level3"
    },
    {
     "expr": "engine:num_files_at_level4{job=$data_type}",
     "legendFormat": "engine:num_files_at_level4"
    },
    {
     "expr": "engine:num_files_at_level5{job=$data_type}",
     "legendFormat": "engine:num_files_at_level5"
    },
    {
     "expr": "engine:num_files_at_level6{job=$data_type}",
     "legendFormat": "engine:num_files_at_level6"
    }
   ]
  },
  {
   "title": "compression_ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:compression_ratio_at_level0{job=$data_type}",
     "legendFormat": "engine:compression_ratio_at_level0"
    },
    {
     "expr": "engine:compression_ratio_at_level1{job=$data_type}",
     "legendFormat": "engine:compression_ratio_at_level1"
    },
    {
     "expr": "engine:compression_ratio_at_level2{job=$data_type}",
     "legendFormat": "engine:compression_ratio_at_level2"
    },
    {
     "expr": "engine:compression_ratio_at_level3{job=$data_type}",
     "legendFormat": "engine:compression_ratio_at_level3"
    },
    {
     "expr": "engine:compression_ratio_at_level4{job=$data_type}",
     "legendFormat": "engine:compression_ratio_at_level4"
    },
    {
     "expr": "engine:compression_ratio_at_level5{job=$data_type}",
     "legendFormat": "engine:compression_ratio_at_level5"
    },
    {
     "expr": "engine:compression_ratio_at_level6{job=$data_type}",
     "legendFormat": "engine:compression_ratio_at_level6"
    }
   ]
  },
  {
   "title": "engine:actual_delayed_write_rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:actual_delayed_write_rate{job=$data_type}",
     "legendFormat": "engine:actual_delayed_write_rate"
    }
   ]
  },
  {
   "title": "rate $rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "repeat": "rate",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate($rate{job=$data_type}[1m])",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "cfstats rate $cfstats_rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 45 },
   "repeat": "cfstats_rate",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L0:$cfstats_rate\"}[1m])",
     "legendFormat": "L0"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L1:$cfstats_rate\"}[1m])",
     "legendFormat": "L1"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L2:$cfstats_rate\"}[1m])",
     "legendFormat": "L2"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L3:$cfstats_rate\"}[1m])",
     "legendFormat": "L3"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L4:$cfstats_rate\"}[1m])",
     "legendFormat": "L4"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:Sum:$cfstats_rate\"}[1m])",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "cfstats actual $cfstats_actual",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 72 },
   "repeat": "cfstats_actual",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L0:$cfstats_actual\"}",
     "legendFormat": "L0"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L1:$cfstats_actual\"}",
     "legendFormat": "L1"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L2:$cfstats_actual\"}",
     "legendFormat": "L2"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L3:$cfstats_actual\"}",
     "legendFormat": "L3"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L4:$cfstats_actual\"}",
     "legendFormat": "L4"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:Sum:$cfstats_actual\"}",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "cfstat io_stalls $io_stalls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 90 },
   "repeat": "io_stalls",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"io_stalls:$io_stalls\"}",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "aggregated table properties $leveldataflag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 117 },
   "repeat": "leveldataflag",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:aggregated_table_properties{job=$data_type,flag=$leveldataflag}",
     "legendFormat": "aggregated"
    },
    {
     "expr": "engine:aggregated_table_properties_at_level0{job=$data_type,flag=$leveldataflag}>0",
     "legendFormat": "level0"
    },
    {
     "expr": "engine:aggregated_table_properties_at_level1{job=$data_type,flag=$leveldataflag}>0",
     "legendFormat": "level1"
    },
    {
     "expr": "engine:aggregated_table_properties_at_level2{job=$data_type,flag=$leveldataflag}>0",
     "legendFormat": "level2"
    },
    {
     "expr": "engine:aggregated_table_properties_at_level3{job=$data_type,flag=$leveldataflag}>0",
     "legendFormat": "level3"
    },
    {
     "expr": "engine:aggregated_table_properties_at_level4{job=$data_type,flag=$leveldataflag}>0",
     "legendFormat": "level4"
    },
    {
     "expr": "engine:aggregated_table_properties_at_level5{job=$data_type,flag=$leveldataflag}>0",
     "legendFormat": "level5"
    },
    {
     "expr": "engine:aggregated_table_properties_at_level6{job=$data_type,flag=$leveldataflag}>0",
     "legendFormat": "level6"
    }
   ]
  }
 ]
}